client/spring-zeebe/src/main/java/io/zeebe/spring/client/annotation/ZeebeTaskListener.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/ZeebeClientConfiguration.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/processor/DeploymentPostProcessor.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/processor/SubscriptionBuilderPostProcessor.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/processor/TaskHandlerPostProcessor.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/processor/TopicHandlerPostProcessor.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/event/EventPublisher.java
client/spring-zeebe/src/test/java/io/zeebe/spring/client/util/ZeebeExpressionResolverTest.java
examples/starter/src/main/java/io/zeebe/spring/example/StarterApplication.java
pom.xml

- fix all checkstyle violations
- also disable addition of license headers by maven, not sure if this is wanted, if you want to use the license header plugin we should reconfigure the copyright owner I guess

Fix checkstyle violations

---

client/spring-zeebe/src/main/java/io/zeebe/spring/client/annotation/ZeebeTaskListener.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/CreateDefaultTopic.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/SpringZeebeClient.java
pom.xml

Hi @jangalinski,
I started to migrate spring-zeebe to the upcoming 0.7.0 changes. As 0.7.0 is not yet released this is more a tracking pull requests. But currently it at least compiles and the examples work. Feel free to add more changes to the branch.
Cheers,
Sebastian

Upgrade to Zeebe 0.7.0

---

pom.xml

chore(root-pom): adjust distribution repos

---

broker/spring-zeebe-broker/src/test/java/io/zeebe/spring/broker/fn/ReadTomlFileTest.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/ZeebeClientLifecycle.java
pom.xml

Update Zeebe to version 0.18.0. Open to your review :)

Update Zeebe to version 0.18.0

---

client/spring-zeebe/src/main/java/io/zeebe/spring/client/annotation/ZeebeWorker.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/processor/ZeebeWorkerPostProcessor.java
examples/worker/src/main/resources/application.yaml

* use job timeout from config if it is not defined by @ZeebeWorker
* use worker maxJobsActive from config if it is not defined by @ZeebeWorker
closes #88 
closes #89

fix(client): use default values for job workers from config

---

client/spring-zeebe-starter/pom.xml
client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/actuator/ZeebeClientHealthIndicator.java
client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/config/ZeebeActuatorConfiguration.java
client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java

Zeebe Health Indicator using Spring Actuator as optional dependency.
Closes #79

zeebe client health indicator

---

client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/ZeebeClientSpringConfiguration.java

Relax dependency as discussed in https://github.com/zeebe-io/spring-zeebe/issues/107

chore(interface) relax some more from ZeebeClientImpl to ZeebeClient

---

client/spring-zeebe/src/main/java/io/zeebe/spring/client/annotation/ZeebeWorker.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/bean/MethodInfo.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/bean/value/ZeebeWorkerValue.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/bean/value/factory/ReadZeebeWorkerValue.java
client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/processor/ZeebeWorkerPostProcessor.java
client/spring-zeebe/src/test/java/io/zeebe/spring/client/bean/ClassInfoTest.java
client/spring-zeebe/src/test/java/io/zeebe/spring/client/bean/value/factory/ReadZeebeWorkerValueTest.java

@salaboy this is basically https://github.com/zeebe-io/spring-zeebe/pull/97 (commit from @wenminglei properly cherrypicked)  with an additional commit on top to add some trivial unit testing.
Not sure this is what you had in mind, do not hesitate to provide feedback if you had something better in mind.

104 more configurations

---

README.md

#109: Add an example of using a custom `JsonMapper`

---

README.md
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/ZeebeDeployment.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/bean/value/ZeebeDeploymentValue.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/bean/value/factory/ReadZeebeDeploymentValue.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/config/processor/DeploymentPostProcessor.java
client/spring-zeebe/src/test/java/io/camunda/zeebe/spring/client/bean/value/factory/ReadZeebeDeploymentValueTest.java
client/spring-zeebe/src/test/java/io/camunda/zeebe/spring/client/config/processor/DeploymentPostProcessorTest.java

* feat(spring-zeebe): support configure resources with classpath:*
* be compatible with "classPathResources" and mark it as deprecated

support configure resources with classpath:*

---

client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/config/ZeebeClientSpringConfiguration.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/exception/DefaultCommandExceptionHandlingStrategy.java

Fix DefaultCommandExceptionHandlingStrategy bean injection issue

---

client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/config/processor/DeploymentPostProcessor.java

The Java client was already able to deploy DMN decision models, deploy DMN decision models via new deploy resource rpc.

Deploy DMN decision models via new deploy resource rpc

---

README.md

The current link leads to a 404

Fix link to Zeebe Java Client

---

.github/workflows/mvn-build.yml
README.md
client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java
client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/properties/PropertyBasedZeebeWorkerValueCustomizer.java
client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
client/spring-zeebe-starter/src/test/java/io/camunda/zeebe/spring/client/properties/ZeebeClientSpringConfigurationPropertiesTest.java
client/spring-zeebe/pom.xml
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/ZeebeWorker.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/customizer/ZeebeWorkerValueCustomizer.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/processor/AnnotationProcessorConfiguration.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/processor/ZeebeWorkerAnnotationProcessor.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/value/ZeebeWorkerValue.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/value/factory/ReadAnnotationValueConfiguration.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/value/factory/ReadZeebeWorkerValue.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/bean/CopyNotNullBeanUtilsBean.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientProperties.java
client/spring-zeebe/src/test/java/io/camunda/zeebe/spring/client/bean/ClassInfoTest.java
client/spring-zeebe/src/test/java/io/camunda/zeebe/spring/client/bean/CopyNotNullBeanUtilsBeanTest.java
client/spring-zeebe/src/test/java/io/camunda/zeebe/spring/client/bean/value/factory/ReadZeebeWorkerValueTest.java
pom.xml
test/embedded/pom.xml
test/embedded/src/test/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerTest.java
test/testcontainer/src/test/java/io/camunda/zeebe/spring/client/jobhandling/SmokeTest.java

So, it could be disabled in the `ZeebeWorker` annotation and via configuration properties.
Closed #220

feat: Add ability to disable workers.

---

README.md

Updated all uses of overwrite to override.
Added note to 'Programmatically completing jobs' section regarding issue 278.

(docs) - minor updates to README.md and issue 278

---

client/spring-zeebe-starter/pom.xml
client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java
client/spring-zeebe-starter/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfigurationTest.java
connector-runtime/pom.xml
connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/configs/LocalContextBeanConfiguration.java
connector-runtime/src/test/java/io/camunda/connector/runtime/ObjectMapperSerializationTest.java
connector-runtime/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java

register Module JavaTimeModule in zeebeObjectMapper for parse OffsetDateTime.
close:
https://github.com/camunda-community-hub/spring-zeebe/issues/293

fix(JsonMapper): register Module JavaTimeModule for parse OffsetDateTime

---

client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/actuator/MicrometerMetricsRecorder.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/metrics/DefaultNoopMetricsRecorder.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/metrics/MetricsRecorder.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/metrics/SimpleMetricsRecorder.java

https://github.com/camunda/team-connectors/issues/289 
related to #305

feat(metrics): collect execution time metrics

---

pom.xml

Bump connectors SDK to 0.6.0-alpha5

deps(connectors-sdk): bump to 0.6.0-alpha5

---

pom.xml

deps(connectors-sdk): bump to 0.6.0

---

client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/bean/MethodInfo.java
client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java

I modified the catch-throw block, so we could throw not only `RuntimeException`s but `Exception`s too
Closes #347

feat(): catch and throw exceptions too

---

connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java
connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistry.java
pom.xml

Connectors SDK version bump
Also closes #340

chore(connectors): bump sdk to 0.7.0-alpha3

---

README.md

The example code looks wrong, as it overrides the default behavior of autoComplete.

add missing autoComplete = false

---

pom.xml

Includes a fix for https://github.com/camunda/connector-sdk/issues/429
related to https://github.com/camunda/team-connectors/issues/381

chore(connectors): bump sdk to 0.8.1

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/actuator/MicrometerMetricsRecorder.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/metrics/DefaultNoopMetricsRecorder.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/metrics/MetricsRecorder.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/metrics/SimpleMetricsRecorder.java

Improvements to support the new Connectors metrics (see https://github.com/camunda/connectors-bundle/pull/678).
- `increase` method now supports an arbitrary increment number
- in Micrometer implementation, if tags are missing or empty, they are not added to the metric

feat(metrics): improve MetricsRecorder interface

---

README.md

DevEx has concluded our search for a Java Spring dev to support turning this project into a full SDK experience! 🚀

Remove job ad

---

README.md

This costed about 5 hours of work from 7 people yesterday. I hope others can benefit from our wasted time.

Changed examples and README to match reality

---

pom.xml
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/OperateClientConfigurationProperties.java

bring the possibility to force keycloak token url rather than building it from the realm and the base url

Fix issue for keycloak17

---

README.md
pom.xml

Making all links working and bumps this library to the latest version
- bump to latest version
- correct markdown syntax
- change some words (british english maybe?) towards american english which is more appropriate in the context

Fix readme 8.2.4

---

.github/CODE_OF_CONDUCT.md
README.md

Changes
- add table of contents
- update code of conduct and contact info

chore(docs): Table of Contents & Code of Conduct

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation_issue.md
.github/ISSUE_TEMPLATE/feature_request.md

Introducing issue templates for easier triaging and auto labeling. Inspired from Zeebe's issue templates.

chore(docs): Issue Templates

---

spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java

Error without variables

---

spring-client-annotations/src/main/java/io/camunda/zeebe/spring/client/annotation/Variable.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java
test/embedded/src/test/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerTest.java

Added name field to variable

---

spring-boot-starter-camunda/pom.xml

Added slf4j dependency to enforce correct version on transitive dependency

---

pom.xml
spring-client-zeebe/pom.xml
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/bean/MethodInfo.java
test/embedded/pom.xml
test/testcontainer/pom.xml

pull request for [issues-511](https://github.com/camunda-community-hub/spring-zeebe/issues/511)

fix parameterNameDiscoverer for work with spring boot 3.2.0

---

camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/CamundaOperateClient.java
camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/search/DecisionDefinitionFilter.java
camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/search/DecisionInstanceFilter.java
camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/search/DecisionRequirementsFilter.java
camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/search/FlowNodeInstanceFilter.java
camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/search/IncidentFilter.java
camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/search/ProcessDefinitionFilter.java
camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/search/ProcessInstanceFilter.java
camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/search/VariableFilter.java

Adding static to builder methods so its easier to create the operate client and build search queries in one line.

Adding static to builder functions

---

.github/workflows/mvn-build.yml
README.md
pom.xml
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java

This will prepare the project to release 8.4.x

Prepare for 8.4.x branch

---

.github/workflows/mvn-release.yml

Spring Zeebe will support releasing multiple product versions so we need to update maven release configuration

Update maven release process 

---

README.md
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/DefaultNoopAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthenticationBuilder.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/CamundaAutoConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CamundaOperateClientConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/OperateClientProdAutoConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/condition/CamundaOperateClientCondition.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/condition/OperateClientCondition.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/CamundaOperateClientConfigurationProperties.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/OperateClientConfigurationProperties.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/common/Client.java

Backport for https://github.com/camunda-community-hub/spring-zeebe/pull/554

[backport] Support old and new operate properties schema

---

camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/JwtCredential.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthenticationBuilder.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthentication.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/CamundaOperateClientConfigurationProperties.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/common/Client.java

This will fix https://github.com/camunda-community-hub/spring-zeebe/issues/560
Changes:
- allow authUrl and baseUrl customization
- refactor SaaSAuthentication

feat: refactor to support authUrl and baseUrl

---

pom.xml
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/CamundaOperateClientConfigurationProperties.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/OperateClientConfigurationProperties.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfigurationCustomJsonMapperTest.java

Use Java 8 functionalities for backward compatibility with our customers

feat: use java 8 functions

---

camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/OperateClientConfiguration.java

Fixing Simple Authentication so Operate works with Basic mode

feat: simple authentication and refactor logging

---

camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/JwtCredential.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleConfig.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleCredential.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSaasOperateCredentialTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSaasZeebeCredentialTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedBasicTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedKeycloakTokenUrlTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedKeycloakUrlTest.java

Adding high level sanity unit tests for different combinations of authentication for Operate
- Cloud
- Self Managed
- Super basic
as well as mix and match application properties

Adding Operate Unit Tests

---

pom.xml

feat: bump zeebe 8.3.5

---

camunda-sdk-java/java-common/src/main/java/io/camunda/common/http/DefaultHttpClient.java

Bring [hotfix](https://github.com/camunda-community-hub/spring-zeebe/pull/591) to `main`

fix: close http response properly

---

camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java

fix(http): Close the http client resources in the SDK authentication

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/CommonConfigurationProperties.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/common/Client.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/common/Keycloak.java

Before the refactoring of the client configuration, the whole config was printed on startup.
This PR re-introduces this to verify whether all configuration has been applied correctly.

feat(config): Re-introduce toString() methods for configuration

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientAllAutoConfiguration.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/ZeebeClientExecutorService.java

made exector service configurable again

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientAllAutoConfiguration.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/ZeebeClientExecutorService.java

backport/8.4: made executor service configurable again

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientAllAutoConfiguration.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/ZeebeClientExecutorService.java

backport/8.3: made exector service configurable again

---

pom.xml

chore(identity): Update the identity dependencies to 8.4.3. 
Enforce non-snapshot versions for releases.
Resolves #626

chore(identity): Update the identity dependencies to 8.4.3. 

---

camunda-sdk-java/java-client-operate/pom.xml
camunda-sdk-java/java-common/pom.xml
camunda-sdk-java/pom.xml
example/pom.xml
legacy/pom.xml
legacy/spring-zeebe-starter/pom.xml
legacy/spring-zeebe-test-testcontainer/pom.xml
legacy/spring-zeebe-test/pom.xml
legacy/spring-zeebe/pom.xml
pom.xml
spring-boot-starter-camunda/pom.xml
spring-client-annotations/pom.xml
spring-client-common/pom.xml
spring-client-zeebe/pom.xml
test/common/pom.xml
test/embedded/pom.xml
test/testcontainer/pom.xml

went to 8.5.0-SNAPSHOT on main

Cleaned version on main branch

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientAllAutoConfiguration.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobWorkerManager.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/ActivatedJobParameterResolver.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/CustomHeadersResolver.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/DefaultParameterResolverStrategy.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/JobClientParameterResolver.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/ParameterResolver.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/ParameterResolverStrategy.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/VariableResolver.java
spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/VariablesAsTypeResolver.java

This PR moves the calculation of which parameter of a @JobWorker needs to be injected how from execution to instantiation.
This new mechanism is called parameter resolving.
Also, this PR adds extensibility to this parameter resolving by injecting a custom strategy to the job worker manager instead of the default one.
closes #653

improved parameter injection

---

README.md

Updated README.md to communicate about the upcoming changes and new supported SDK for Spring Zeebe

Spring-Zeebe: description update

---

pom.xml
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/common/ZeebeClientProperties.java
spring-boot-starter-camunda/src/main/resources/application-camunda-oidc.yaml
spring-boot-starter-camunda/src/main/resources/application-camunda-saas.yaml
spring-boot-starter-camunda/src/main/resources/application-camunda-simple.yaml
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/CamundaClientPropertiesOidcTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/CamundaClientPropertiesSaasTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/CamundaClientPropertiesSimpleTest.java

* updated zeebe rest api port
* updated zeebe rest api port
* Update CamundaClientPropertiesOidcTest.java
* Update CamundaClientPropertiesSimpleTest.java # Conflicts:
#	spring-boot-starter-camunda/src/main/resources/application-camunda-oidc.yaml #	spring-boot-starter-camunda/src/main/resources/application-camunda-simple.yaml #	spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/CamundaClientPropertiesOidcTest.java #	spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/CamundaClientPropertiesSimpleTest.java

updated zeebe rest api port (#757)

---

README.md

I made small tweaks to @aleksander-dytko's PR, but I'm wondering if we should add more context with an issue directly on this repo as well. I want to make sure functionality and future plans are clear for both repos.

Add more context for Camunda Spring SDK

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/legacy/authentication/OperateSelfManagedBasicTest.java

(cherry picked from commit 44dbac6e24b97c80cf2d80ba204e9fb1402c147b)

use url and baseurl to build, asserted with test (#769)

---

spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/VariableResolver.java

fix: VariableResolver can return null

---

spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/parameter/VariableResolver.java

(cherry picked from commit b1f23c6bcd6b0d8ce5ee7839edcfde9aa41c84c8)

fix: VariableResolver can return null (#771)

---

README.md

Add identity repository on setup

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java

(cherry picked from commit 1e85d70517f28087e345d6c65ed200f8111beff4)

applied default value in case legacy config is used (#787)

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/JsonMapperConfiguration.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/JsonMapperConfigurationTest.java

Backport of https://github.com/camunda-community-hub/spring-zeebe/pull/804

Backporting https://github.com/camunda-community-hub/spring-zeebe/pull/804

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/common/ZeebeClientProperties.java

(cherry picked from commit a23f1643caad5600c632505c7fdc4b737422acb9)

declared nested configuration property (#808)

---

README.md

Document timer testing

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/CamundaAutoConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientAllAutoConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientProdAutoConfiguration.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/condition/ZeebeClientCondition.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/LegacyZeebeClientDisabledTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/LegacyZeebeClientEnabledTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientDisabledTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientEnabledTest.java

(cherry picked from commit 0644b302f948105364ea39aaa459aad3ca1376f2)

fix: both properties work now (#809)

---

spring-client-annotations/src/main/java/io/camunda/zeebe/spring/client/annotation/JobWorker.java

fix: job worker stream disabled by default

---

spring-client-annotations/src/main/java/io/camunda/zeebe/spring/client/annotation/JobWorker.java

(cherry picked from commit 17f6bc70a962c730eba9b339f55903b1492cb051)

fix: job worker stream disabled by default (#813)

---

spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/value/ZeebeWorkerValue.java

(cherry picked from commit 191ea9aeaa155a10c4995f7625df848d87c7ced2)

regression: added deprecated array setter (#823)

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/OperateClientConfiguration.java

(cherry picked from commit 4d2831270bb747b903bd43518c11c9d622f016e8)

regression: added old way of bootstrapping the operate client (#829)

---

camunda-sdk-java/java-client-operate/src/main/java/io/camunda/operate/model/ProcessInstance.java

(cherry picked from commit d423b5609ff29ed76f451afdb20c7619cf13a291)

add missing field to process instance (#847)

---

camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/Authentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/DefaultNoopAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/JwtAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
camunda-sdk-java/java-common/src/main/java/io/camunda/common/http/DefaultHttpClient.java
camunda-sdk-java/java-common/src/test/java/io/camunda/common/http/DefaultHttpClientTest.java
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/AuthenticationConfigurationOidcTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/AuthenticationConfigurationSaasTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/AuthenticationConfigurationSimpleTest.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientConfigurationTest.java

Add the management of CSRF token for the simple authentication (#860)

feat(simple-authentication): add the management of CSRF token 

---

camunda-sdk-java/java-client-operate/pom.xml
example/pom.xml
pom.xml
spring-boot-starter-camunda/pom.xml

(cherry picked from commit 5982adb4679332b6d480053182cf949f12bf6fa7)

make operate client legacy (#885)

---

README.md

add comment about dependency management

---

spring-boot-starter-camunda/pom.xml
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/PropertyBasedZeebeWorkerValueCustomizer.java
spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/PropertyBasedZeebeWorkerValueCustomizerTest.java

(cherry picked from commit 1d965449667f7b4ce8be2ca1c860d2b314c4d608)

bugfix: do not ignore json field names from annotations (#934)

---

README.md

@jonathanlukas : please review this simple fix

fix(docs): The annotation is called @Variable

---

pom.xml
spring-boot-starter-camunda/pom.xml

https://github.com/camunda-community-hub/spring-zeebe/issues/967

fix(deps): returned generating spring metadata file #967

---

camunda-sdk-java/java-common/pom.xml
example/pom.xml
spring-boot-starter-camunda/pom.xml
spring-client-annotations/pom.xml
spring-client-zeebe/pom.xml

* this is all relocated
* this is all relocated
(cherry picked from commit 1926a84e7fc4053781101e82af0a77a13b47b5ce)

Relocation (#985)

---

spring-boot-starter-camunda/pom.xml
spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java

* make spring zeebe compatible with 8.6
* added used dependency
(cherry picked from commit bf637e3839ee5ee9a8e0acf64bcee7eb17d00c52)

make spring zeebe compatible with 8.6 (#1061)

---

spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java

Set new properties from Identity SDK 8.6.15 to avoid compatibility issues for clients that use an older Identity SDK version

Conditional identity config for new properties
