- broker/spring-zeebe-broker/src/main/java/io/zeebe/spring/broker/EnableZeebeBroker.java
- broker/spring-zeebe-broker/src/main/java/io/zeebe/spring/broker/config/SpringZeebeBroker.java
- broker/spring-zeebe-broker/src/main/java/io/zeebe/spring/broker/config/ZeebeBrokerConfiguration.java
- broker/spring-zeebe-broker/src/test/java/io/zeebe/spring/broker/config/ZeebeBrokerConfigurationTest.java
- with commit abfa1e6 a camunda license
header was added to some files
- remove the license header
- since bc88f69 the license header will
not be added anymore by maven
> chore(broker): remove partially added license headers

- .ci/distro_release.dsl
*Note*: as the examples are not build during the release the parent version
in the examples pom is not adjusted and has to be modified manually after the
release.
related to zeebe-io/zeebe#549
> ci(jenkins): add jenkins distro release job

- client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/ZeebeClientLifecycle.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/annotation/ZeebeWorker.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/bean/value/ZeebeWorkerValue.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/bean/value/factory/ReadZeebeWorkerValue.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/processor/ZeebeWorkerPostProcessor.java
- examples/groovy/broker.gsh
- examples/groovy/demoProcess.bpmn
- examples/groovy/job-worker.gsh
- examples/groovy/starter.gsh
- examples/starter/src/main/java/io/zeebe/spring/example/StarterApplication.java
- examples/starter/src/main/resources/demoProcess.bpmn
- examples/worker/src/main/java/io/zeebe/spring/example/WorkerApplication.java
- pom.xml
> Update Zeebe to version 0.17.0

- .gitignore
- pom.xml
This pull request updates Zeebe Client API support to version 0.16.4 as requested by some users. It also updates Spring Boot version to 2.1.4RELEASE.
> Update Spring Boot to version 2.1.4

- client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java
- client/spring-zeebe-starter/src/test/java/io/zeebe/spring/client/properties/ZeebeClientSpringConfigurationDefaultPropertiesTest.java
- client/spring-zeebe-starter/src/test/java/io/zeebe/spring/client/properties/ZeebeClientSpringConfigurationPropertiesTest.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/ZeebeClientSpringConfiguration.java
- examples/starter/src/main/resources/application.yaml
This hopefully close #49 . 
Please @menski and @jangalinski review carefully because a better way to implement this fix should easily exist (due to my low knowledge of spring).
IMHO what's needed: 
. Opened to your feedback!
> Application.yml correctly used by spring-zeebe-starter

- client/spring-zeebe/src/main/java/io/zeebe/spring/client/bean/MethodInfo.java
> Rethrow target exception of job worker invocation

- .gitignore
- .travis.yml
- broker/spring-zeebe-broker/pom.xml
- client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java
- client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
- client/spring-zeebe-starter/src/test/java/io/zeebe/spring/client/properties/ZeebeClientSpringConfigurationDefaultPropertiesTest.java
- client/spring-zeebe-starter/src/test/java/io/zeebe/spring/client/properties/ZeebeClientSpringConfigurationPropertiesTest.java
- pom.xml
- test/pom.xml
Tested with Oracle jdk 11. Tests runs fine.
Maintainers please check:
- Pom changes to support Java 11 (I did several checks on the net to upgrade some plugins and dependencies
- Broker changes: I added new properties introduced in 0.21 java client. Please notify me in case of other functionalities I may have not covered with this PR that can impact spring-zeebe
Issues: this PR is subjected to issue #67 . **Please do not merge until the issue has been closed** (reply from Java Client maintainers needed).
> Support Zeebe 0.21, Spring 2.2.0 and Java 11

- client/spring-zeebe/src/main/java/io/zeebe/spring/client/annotation/ZeebeDeployment.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/bean/value/ZeebeDeploymentValue.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/bean/value/factory/ReadZeebeDeploymentValue.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/processor/DeploymentPostProcessor.java
- client/spring-zeebe/src/test/java/io/zeebe/spring/client/bean/ClassInfoTest.java
- client/spring-zeebe/src/test/java/io/zeebe/spring/client/bean/value/factory/ReadZeebeDeploymentValueTest.java
- client/spring-zeebe/src/test/java/io/zeebe/spring/client/config/processor/DeploymentPostProcessorTest.java
- examples/starter/src/main/java/io/zeebe/spring/example/StarterApplication.java
Hi
I found possibility of deployment only one resource using `ZeebeDeployment` annotation very limiting, not much to modify and it works with multiple resources. Could be useful also for others, let me know what you think.
> Deployment of multiple resources by annotation

- README.md
@salaboy I played around with new configuration properties in a branch in my fork: https://github.com/ArtunSubasi/spring-zeebe/tree/security-configuration
Then I found out that the Camunda Cloud connections work out-of-the-box using environment variables. Therefore, I don't think it is a good idea to add an additional support for the application properties. Since the credentials contain confidential information, they must be encrypted or injected using the environment variables anyway.
This PR only contains an update to the documentation.
> #81 Update documentation for the Camunda Cloud support

- client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java
- client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
- client/spring-zeebe/src/main/java/io/zeebe/spring/client/properties/ZeebeClientProperties.java
- pom.xml
Allow users to introduce their own `JsonMapper`s and `ClientInterceptor`s
closes #109
> #109: Allow users to provide client interceptors and the JsonMapper

- client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
- pom.xml
- update Zeebe dependency to 1.1.0
- add region as new configuration property for cloud
- set default region to `bru-2` to be backwards compatible with all post GA clusters
> Update to Zeebe 1.1.0

- test/pom.xml
`zeebe-test` will be deprecated soon so here we remove it from the dependencies of the `spring-zeebe-test` module. `zeebe-test` wasn't used internally so no further changes were necessary. 
Users of `spring-zeebe` can still add a direct dependency on `zeebe-test` if they need it. 
closes #133
> Remove unused dependency on zeebe-test

- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/ZeebeWorker.java
When trying to use the parameter from the `application.yaml`, the worker could not be started.
Convention is to use `-` instead of camelCase for `application.yaml` files. Usually, spring can resolve this when mapping yaml values to Java classes, but it seems that for an expression, the `-` way is required.
> Bugfix: This could not be interpreted by spring

- README.md
- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/ZeebeCustomHeaders.java
- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/ZeebeHeaders.java
- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java
As of ZeebeVariable and ZeebeVariablesAsType
This feature should enable the possibility to get headers injected :
``` java
@ZeebeWorker(type = "foo", autoComplete = true)
public void handleFoo(final ActivatedJob job, @ZeebeHeaders Map<String, String> headers){
// do whatever you need to do
}
``` 
We could have both variables and headers combined as :
``` java
@ZeebeWorker(type = "foo", autoComplete = true)
public ProcessVariables handleFoo(@ZeebeVariablesAsType ProcessVariables variables, @ZeebeHeaders Map<String, String> headers){
// do whatever you need to do
return variables;
}
```
> Adding @ZeebeHeaders to fetch and inject headers as params

- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/value/factory/ReadZeebeWorkerValue.java
I think that we should rely in this case only on `io.camunda.zeebe.spring.client.annotation.processor.ZeebeWorkerAnnotationProcessor.start` as a single source of truth.
Closes #204
> fix: remove the duplicated worker name initializations

- README.md
- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java
- client/spring-zeebe/src/test/java/io/camunda/zeebe/spring/client/bean/ClassInfoTest.java
- client/spring-zeebe/src/test/java/io/camunda/zeebe/spring/client/bean/value/factory/ReadZeebeWorkerValueTest.java
- test/embedded/src/test/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerTest.java
- test/testcontainer/src/test/java/io/camunda/zeebe/spring/client/jobhandling/SmokeTest.java
Fixes the deserialization of complex types using an ObjectMapper when annotating a worker job method with `@ZeebeVariable`
> fixes ZeebeVariable deserialization

- README.md
- client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java
- client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
- client/spring-zeebe-starter/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfigurationCustomJsonMapperTest.java
- client/spring-zeebe-starter/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfigurationTest.java
- client/spring-zeebe-starter/src/test/java/io/camunda/zeebe/spring/client/properties/ZeebeClientSpringConfigurationPropertiesTest.java
- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/AbstractZeebeBaseClientSpringConfiguration.java
- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java
- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobWorkerManager.java
- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientProperties.java
- test/testcontainer/src/test/java/io/camunda/zeebe/spring/client/jobhandling/SmokeTest.java
Fixes the deserialization of complex types when annotating a worker job method with @ZeebeVariable by using the `JsonMapper` bean when exists in the context, falling back to a plain `ObjectMapper` otherwise
Supersede #236
> fixes ZeebeVariable deserialization using JsonMapper

- client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java
- client/spring-zeebe-starter/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfigurationCustomJsonMapperTest.java
- client/spring-zeebe-starter/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfigurationTest.java
Changes the default jsonMapper bean name to avoid conflicting with other `jsonMapper` beans and autowire custom defined beans of type `JsonMapper`. Also adding some more test cases to catch similar issues in the future.
Should be fixing #240
> Fixes json mapper default naming

- connector-runtime/pom.xml
- pom.xml
Adds the validation module by default to the Connector runtime to provide this for Connectors. Connectors compile against the validation module with scope `provided` to avoid clashes on the final Connector runtime classpath.
> chore(connector-runtime): add validation module by default

- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorProperties.java
Those two configurations are not required by the webhook (the code can work with null values and will apply defaults). So they should not be enforced when parsing the config. 
OK @igpetrov?
> Made activationCondition and variableMapping optional for webhook

- client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/JobWorker.java
Added docs to `@JobWorker` as this is one of the primary interfaces to create workers and they lack important info such as unit of measurement for timeouts.
Most of the wording has been inherited from `io.camunda.zeebe.client.api.worker.JobWorkerBuilderStep1`.
Please double check the UoM for `requestTimeout` (the only one in seconds as opposed to milliseconds). This has been inferred by looking at `JobWorkerManager.java#L77`.
> Adds JavaDocs to @JobWorker

- client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/actuator/ZeebeActuatorConfiguration.java
Make sure that the whole actuator configuration class is only loaded by spring in case actuator is present.
closes #279
> fix(spring): only load actuator config class if actuator is present

- client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/actuator/ZeebeActuatorConfiguration.java
> fix(metrics): Restore default actuator metrics (e.g. `jvm`)

- client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/actuator/MicrometerMetricsRecorder.java
Provides fix of the `camunda_connector_outbound_invocations_total` metric (and subsequently of the similar metric for inbound). See related issue for context.
closes #299
> fix(metrics): include jobType tag in counter key

- README.md
- client/spring-zeebe-starter/src/main/resources/META-INF/spring.factories
- client/spring-zeebe-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- pom.xml
- test/embedded/src/main/java/io/camunda/zeebe/spring/test/ZeebeTestExecutionListener.java
See #289 - Spring Zeebe now works with Spring >= 2.7.6 (also including 3.0.x)
> Prepare for Spring Boot 3

- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/operate/OperateClientFactory.java
- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/operate/OperateClientLifecycle.java
- connector-runtime/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporterTest.java
Implements proper pagination support for Operate `ProcessDefinitionImporter`.
closes #336
> fix: support pagination in Operate ProcessDefinitionImporter

- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/ActiveInboundConnectorResponse.java
- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorRestController.java
Adds an endpoint to retrieve all active inbound connectors.
**Sample response structure:**
```
[
{
"bpmnProcessId": "8b1a3ac7-2edd-4d54-9c65-aa983c65edd8",
"type": "io.camunda:webhook:1",
"data": {
"path": "my-inbound-connector-path"
},
{
"bpmnProcessId": "8b1a3ac7-2edd-4d54-9c65-aa983c65edd8",
"type": "io.camunda:webhook:1",
"data": {
"path": "my-other-inbound-connector-path"
}
}
]
```
**Current limitations:**
In Spring Zeebe runtime, we only know about the internals of the Webhook Connector. The Runtime can't possibly know what data should be displayed in the Modeler for generic inbound connectors (e.g. various subscriptions).
We will need to evolve this into a more robust and generic solution, that would allow Connector developers to indicate what information about the inbound …
> feat(connectors): add endpoint to retrieve active inbound connectors

- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
- connector-runtime/src/test/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestControllerTest.java
Enables correct handling of requests with empty body for inbound webhook connector.
closes #344
> fix(webhook): support empty body for webhook inbound connector

- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorRestController.java
Missing null check resulted in error 500 when invalid `bpmnProcessId` is provided.
> fix(connectors): missing null check in 'active inbound' endpoint

- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistry.java
- connector-runtime/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerPlainJavaTests.java
Adds another check to webhook `containsContextPath` method, so that webhook endpoint consistently returns 404 in both cases:
- if webhook has not been activated
- if webhook was deactivated by deploying a new process definition without connector
closes #370
> fix(connectors): handle disable webhook correctly, return 404

- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java
- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorProperties.java
- connector-runtime/src/main/resources/application.properties
- connector-runtime/src/test/java/io/camunda/connector/runtime/inbound/TestInboundConnector.java
- connector-runtime/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java
- connector-runtime/src/test/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManagerTest.java
- pom.xml
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/OperateClientProdAutoConfiguration.java
Adjustments to Connector runtime to support the [changes in the Connector SDK](https://github.com/camunda/connector-sdk/pull/411):
- Variable mapping and activation condition check are now handled centrally in the SDK (added deprecation warning to legacy checks in webhook connector)
- Adjustments to support slightly changed APIs
- Cancellation callback handling (initial simple implementation, just deregisters the connector without storing the error). Will be improved as a follow up: #401
> feat(connectors): bump connector-sdk

- pom.xml
- spring-boot-starter-camunda/pom.xml
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/OperateClientProdAutoConfiguration.java
Currently, if the operate failed to start-up before connectors, the whole Spring Zeebe runtime crashes.
This happens in 100% of cases when launching with `camunda-platform`.
Output logs on startup:
```
2023-04-06 13:02:29.662  WARN 17490 --- [           main] s.c.c.OperateClientProdAutoConfiguration : An attempt to connect to Operate failed: io.camunda.operate.exception.OperateException: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:8081 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
2023-04-06 13:02:34.677  WARN 17490 --- [           main] s.c.c.OperateClientProdAutoConfiguration : An attempt to connect to Operate failed: io.camunda.operate.exception.OperateException: org.apache.hc.client5.http.HttpHostConnectException: …
```
> chore(operate-client): introduced retry mechanism on create

- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
- connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
Fixes the issue by using the methods and constructors which are compatible with both Spring Boot versions.
Also, adds a minor improvement in process definition importing that makes it fail-safe (log error and proceed with other process definitions).
closes #404
> Fix `NoSuchMethod` on webhook call with Spring Boot 3

- pom.xml
- spring-client-zeebe/pom.xml
This module was removed from the Connnector SDK.
It is no longer required in Spring Zeebe either, since the Connector runtime was moved to another project.
> chore(connectors): rm connectors runtime util

- spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/bean/MethodInfo.java
As mentioned in issue #426 we want to hide some aspects needed for each of the service-tasks. One thing we do is do pass entity loaded from a repository to the business method.
This PR is about some minor adoptions to leverage `ZeebeWorkerValueCustomizer` this purpose by injecting a custom `MethodInfo` which is aware of the new parameters. For this some minor adopts of `MethodInfo` is needed to make the class extendable.
We tested this within the last month and it works fine. We would be glad to see this merged 😄 .
> @JobWorker: Pass custom args to business method

- README.md
Please double check: this documentation seems out-dated because the artifact was moved to `io.camunda.spring:spring-boot-starter-camunda`
> Update to current artifact, replacing the deprecated coordindates

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
Prevents a `CredentialsProvider` with an empty clientId when trying to overwrite property to disable oauth. Fixes #450
> prevent CredentialsProvider with empty clientId

- pom.xml
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ExecutorServiceConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientAllAutoConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientProdAutoConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
- spring-client-zeebe/src/test/java/io/camunda/zeebe/spring/client/processor/DeploymentPostProcessorTest.java
This upgrades the dependencies for the zeebe and operate clients to the latest alpha versions to allow the connectors component to make use of multi-tenancy. This also includes an update of the jackson dependency as the previous pom did not provide an up-to-date version that was compatible with the zeebe client.
> chore: Upgrade dependencies for multi-tenancy alpha support

- README.md
The previous matrix is okay but might be outdated. Wanted to see if an expanded version will be better. The old matrix is simpler but might omit some tiny details. The new matrix includes the following:
- JDK scope was included till 8 (not sure if its worth to include 8 given its End of Life already)
- Added separate rows for JDK 17 (only required for SB 3.x)
> chore(docs): update version matrix

- spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/exception/ZeebeBpmnError.java
- spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java
As mentioned in #395, `zeebe-client-java` already supports sending variables along with the ThrowErrorCommand. This adds the ability to optionally update context variables when throwing `ZeebeBpmnError`
> Resolves #395 Add variables in ZeebeBpmnError

- pom.xml
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
Fixes https://github.com/camunda-community-hub/spring-zeebe/pull/473 and https://github.com/camunda-community-hub/spring-zeebe/issues/470
SpringBoot 3 requires the use of `jakarta` packages instead of `javax`
> Update Spring Boot dependency to 3.1.4

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientProdAutoConfiguration.java
Related to https://github.com/camunda-community-hub/spring-zeebe/issues/483. On application startup, Spring tries to read the value of [scheduledExecutorService](https://github.com/camunda-community-hub/spring-zeebe/blob/233ebd35322a37ffe886b4d52e56aff182d0049d/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java#L273-L274). It then finds it as `null` so [autowiring](https://github.com/camunda-community-hub/spring-zeebe/blob/472e9e402a7e7712742e95e491cf1ad6d0002805/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java#L86-L87) is initiated but there is no bean available so it throws 
```
NoSuchBeanDefinitionException: No qualifying bean of type …
```
> Fix missing ScheduledExecutorService during startup

- spring-client-zeebe/pom.xml
According to this [issue](https://github.com/camunda-community-hub/spring-zeebe/issues/414) we have [vulnerable](https://devhub.checkmarx.com/cve-details/Cx78f40514-81ff/) transitive dependency `commons-collections` under `spring-client-zeebe`.
Things we know:
- Updating to latest Spring Boot 3 won't solve the issue since its not a dependency of SB3
- Inspected the [code](https://github.com/camunda-community-hub/spring-zeebe/blob/405ddeae5dba13863d9b1910670b40e923661b9c/spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/bean/CopyNotNullBeanUtilsBean.java#L3-L3) and looks like we are not using any functionality of `commons-collections` (it gets imported as part of commons-beanutils). There are no known reference for commons-collections in the repo
We have few options:
- …
> chore: exclude commons-collections dependency

- spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobWorkerManager.java
- spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/metrics/ZeebeClientMetricsBridge.java
Zeebe's java-client has JobWorker [metrics](https://github.com/camunda-community-hub/spring-zeebe/issues/472) and explicitly enabling it on `spring-zeebe`
Zeebe-client metrics gets translated towards Spring's `MetricRecorder` so that users will see consistent metrics in the format of `metric` and `action`.
- enabled by default (can be disabled by config property if there is a need?)
- users will see 2 sets of metrics in the same format:
- `camunda.job.invocations` (from spring)
- `zeebe.client.worker.job` (from zeebe-client)
> Enable Java Client / JobWorker Metrics

- README.md
Updating the readme to reflect usage of new compiler flag for new versions of Spring-Zeebe related to this PR https://github.com/camunda-community-hub/spring-zeebe/pull/512
This is the first time i'm aware of the `-parameters` flag but it seems its common based on a[ quick github search](https://github.com/search?q=%3Carg%3E-parameters%3C%2Farg%3E+&type=code)
> Adding instruction for new compiler flag

- example/pom.xml
Adding `-parameters` flag in `example` module. This was missed in previous [PR](https://github.com/camunda-community-hub/spring-zeebe/pull/512)
> Adding compiler flag in example

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/common/Client.java
Our dependencies used the field `username` instead of `user`. Also the rest of Camunda docs uses `username` so its good to have consistency
> feat: change user to username

- pom.xml
As described in this issue https://github.com/camunda-community-hub/spring-zeebe/issues/536, overriding the io.grpc to the fixed version till SpringBoot patch is released
> feat: workaround for grpc issue

- .github/workflows/mvn-release.yml
Using Java 21 since Zeebe 8.4 uses that JDK version
> Use Java 21 for publish artifacts

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
`zeebe-client` is adding [scope](https://github.com/camunda/zeebe/pull/15404) as part of authentication. Supporting it here as well.
This will fail since `zeebe-client` hasn't released the version yet. Once released, PR will be modified to bump the version
> Add scope in credentials

- pom.xml
I was incorrectly using the dependency management. It turns out, we need to specify the dependencies so that it actually overrides the version.
We should not be specifying dependencies in the root pom of the project. But this will be an exception since the other approach would be to duplicate the dependencies on two modules `spring-boot-starter-camunda` and `spring-boot-starter-camunda-test` which is not clean
> feat: correct the way we override dependencies

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CamundaOperateClientConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/condition/CamundaOperateClientCondition.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/condition/OperateClientCondition.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/CamundaOperateClientConfigurationProperties.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/OperateClientConfigurationProperties.java
To enable operator client, users can set the `baseUrl` or `authUrl`. This will use the existing zeebe credentials present.
Both schemes below are valid.
```
zeebe.client.cloud.region=xxx
zeebe.client.cloud.clusterId=xxx
zeebe.client.cloud.clientId=xxx
zeebe.client.cloud.baseUrl=xxx
camunda.operate.client.base-url=operate.camunda.io
camunda.operate.client.auth-url=https://login.cloud.camunda.io/oauth/token
zeebe.client.cloud.region=xxx
zeebe.client.cloud.clusterId=xxx
zeebe.client.cloud.clientId=xxx
zeebe.client.cloud.baseUrl=xxx
operate.client.base-url=operate.camunda.io
operate.client.auth-url=https://login.cloud.camunda.io/oauth/token
```
> Enable Operator Client via authUrl or baseUrl

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/CamundaOperateClientConfigurationProperties.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/OperateClientConfigurationProperties.java
We need to get the correct baseUrl for cloud instances. All this time we were hardcoding cloud base url to be `operate.camunda.io` (PROD) but we need to account there can be multiple environments.
> Get correct base url for Cloud instances

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ExecutorServiceConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientProdAutoConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfigurationCustomJsonMapperTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/ZeebeClientSpringConfigurationPropertiesTest.java
As mentioned in #558 we want to use spring-zeebe to connect to a self-managed cluster having tenants enabled. This also requires to enable Identity based authentication (see https://github.com/camunda/camunda-platform#multi-tenancy).
I used the current main-branch (https://github.com/camunda-community-hub/spring-zeebe/commit/17e1fc4d9109a46c8952f380755fa18b459e396b) to test this, but failed due to two lacks in implementation:
1. At https://github.com/camunda-community-hub/spring-zeebe/blob/17e1fc4d9109a46c8952f380755fa18b459e396b/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java#L41 it is tested for `getCloud() != null` but there is always an object given.
2. At https://github.com/camunda-community-hub/spring-zeebe/blob/17 …
> Use Authentication for ZeebeClient

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java
Due to this [PR](https://github.com/camunda-community-hub/spring-zeebe/pull/559) users will be stuck using Zeebe GRPC header authentication. Modifying the condition so customers not using the `common.` properties will still be able to use their own Zeebe variables
> feat: adding correct condition to avoid being stuck on zeebe header auth

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java
`scope` and other 8.4 was accidentally introduced in 8.3 (was supposed to be in 8.4). Undoing it.
> feat: remove accidental 8.4 features

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthenticationBuilder.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/condition/OperateClientCondition.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/OperateClientConfigurationProperties.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/common/Keycloak.java
Allows Self-Managed users to specify `keycloakTokenUrl` directly to allow customized keycloak instances
> feat: support keycloakTokenUrl for Self-Managed

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
There can be instances where multiple `Set-Cookie` headers are returned. We need to pick the one that says `Operate-Session`.
Unit tests to follow and as of now, it was hard-coded for `Operate-Session` since only Operate module is supported.
We can see from above that cookies that start from `Operate-Session` is picked.
> Handle multiple Set-Cookie during Simple Authentication

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/Authentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/DefaultNoopAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/http/DefaultHttpClient.java
- camunda-sdk-java/java-common/src/test/java/io/camunda/common/http/DefaultHttpClientTest.java
- Add token reset for authentication failures
- Throw exceptions instead of swallowing
TODOs:
- Refactor the duplicate code introduced
- Handle automatic retry of existing request if authentication has expired
- Make code unit testable to add unit tests and mock authentication process
> Add token reset and throw exception instead of swallowing

- spring-boot-starter-camunda/pom.xml
Add compiler flag to avoid https://github.com/camunda-community-hub/spring-zeebe/pull/514 when running tests for `spring-boot-starter-camunda`
> chore(build): Add missing compiler arg

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
Fixes the [issue](https://github.com/camunda-community-hub/spring-zeebe/issues/589) by using dynamic cookie header prefix per product
> feat: use dynamic prefix for product

- pom.xml
Removing the override netty BOM since Zeebe 8.4.0 already has `1.60.0`
> chore: remove previously override netty bom

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedBasicWithZeebeCredentialsTest.java
There was a regression during refactoring for Identity SDK integration. The JWT was moved to a higher scope but it fails since its being evaluated first before checking if its a basic mode.
Changes:
- move the configuring jwts to their respective local scopes inside different conditions
- refactor and add more tests to avoid false positive
> Fix self managed basic auth

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/Authentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/DefaultNoopAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/JwtAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/JwtAuthenticationBuilder.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthenticationBuilder.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthenticationBuilder.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthenticationBuilder.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/CamundaAutoConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfigurationCustomJsonMapperTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSaasOperateCredentialTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSaasZeebeCredentialTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedBasicTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedKeycloakTokenUrlTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedKeycloakUrlTest.java
Currently, the token provider not refresh a token unless it is reported invalid by the server.
This behaviour does not work with the zeebe client.
This fix refactors the jwt authentication to check the validity of a token BEFORE sending the request and eventually refreshing the token upfront.
closes #631
> backport/8.3: fix(common-authentication): Token not refreshed

- .github/workflows/mvn-build.yml
- .github/workflows/mvn-release.yml
- camunda-sdk-java/java-client-operate/pom.xml
- camunda-sdk-java/java-common/pom.xml
- example/pom.xml
- pom.xml
- spring-boot-starter-camunda/pom.xml
- spring-client-annotations/pom.xml
- spring-client-common/pom.xml
- spring-client-zeebe/pom.xml
closes #623 
closes #558 
It seems that the majority of the artefacts is still built for Java 8!
This PR leaves Java 17 in place and enforces that the according compiler version is used.
> Revert to Java 17 compiled artefacts

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/Authentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/DefaultNoopAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/JwtAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/JwtAuthenticationBuilder.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/JwtConfig.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthenticationBuilder.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SelfManagedAuthenticationBuilder.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthenticationBuilder.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleConfig.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/CamundaAutoConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfigurationCustomJsonMapperTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSaasOperateCredentialTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSaasZeebeCredentialTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedBasicTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedBasicWithZeebeCredentialsTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedIdentityTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedKeycloakTokenUrlTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/authentication/OperateSelfManagedKeycloakUrlTest.java
Currently, the token provider not refresh a token unless it is reported invalid by the server.
This behaviour does not work with the zeebe client.
This fix refactors the jwt authentication to check the validity of a token BEFORE sending the request and eventually refreshing the token upfront.
closes #631
> backport/8.4: fix(common-authentication): Token not refreshed

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/actuator/MicrometerMetricsRecorder.java
closes #620
fixed a bug where race condition while creating counter in MicrometerMetricsRecorder, prevent JobWorker handler loss at start in rare cases.
> issue-620 fixed a bug where race condition while creating counter.

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java
> ensure that only one instance of a credential provider exists

- README.md
This PR add multi-tenancy config to the docs.
These snippets are untested and I am unsure how a List of Strings can be expressed in a properties file.
Otherwise, each of these snippets should also have a list expression example...
> Added tenant config to docs

- README.md
- pom.xml
- spring-boot-starter-camunda/pom.xml
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/common/ZeebeClientProperties.java
- spring-boot-starter-camunda/src/main/resources/application-camunda-oidc.yaml
- spring-boot-starter-camunda/src/main/resources/application-camunda-saas.yaml
- spring-boot-starter-camunda/src/main/resources/application-camunda-simple.yaml
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/legacy/ZeebeClientStarterAutoConfigurationCustomJsonMapperTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/legacy/ZeebeClientStarterAutoConfigurationTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/CamundaClientPropertiesOidcTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/CamundaClientPropertiesSaasTest.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/CamundaClientPropertiesSimpleTest.java
Hello,
I wanted to use spring-zeebe with Zeebe 8.5.0 that have now a REST API
I will set zeebe version with 8.5.0 once it is released this week
> chore: prepare bump zeebe version to 8.5.0

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/JwtAuthentication.java
…seconds (#775)
(cherry picked from commit 6cd49349fcac7105da469b0690f5b1b98beff266)
> fix: a token is only counted valid if the expiry is later than in 30 seconds

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/JsonMapperConfiguration.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/JsonMapperConfigurationTest.java
We can't set a process variable to null, because the ObjectMapper was configured to ignore NULL values.
This was a side effect due to the `ZeebeObjectMapper` and `SdkObjectMapper` using the `objectMapper` and mutating it.
To avoid breaking things, I just copied the initial mapper to keep the current behavior for the said mappers while avoiding the mutations.
I plan to backport this in: 
- 8.4
- 8.5
closes https://github.com/camunda/connectors/issues/2648
> bug(object-mapper): Fix our custom mappers creation to avoid mutating the initial ObjectMapper

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/AuthenticationConfigurationSimpleTest.java
Backport of #836 
* fix(simple-authentication): Fix an issue with SimpleAuthentication when CRSF protection is enabled (multiple Set-Cookie headers)
> fix(simple-authentication): Fix an issue with SimpleAuthentication (#836)

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/config/AuthenticationConfigurationSimpleTest.java
Backport of #836
* fix(simple-authentication): Fix an issue with SimpleAuthentication when CRSF protection is enabled (multiple Set-Cookie headers)
> fix(simple-authentication): Fix an issue with SimpleAuthentication

- spring-boot-starter-camunda/pom.xml
- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/PropertyBasedZeebeWorkerValueCustomizer.java
- spring-boot-starter-camunda/src/test/java/io/camunda/zeebe/spring/client/properties/PropertyBasedZeebeWorkerValueCustomizerTest.java
> bugfix: do not ignore json field names from annotations

- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java
- camunda-sdk-java/java-common/src/main/java/io/camunda/common/http/DefaultHttpClient.java
Currently, the underlying HTTP clients cannot be configured to use a proxy (which is unfortunately needed quite of the enterprise environments)
Therefore I suggest this PR to support e.g. http_proxy and https_proxy
> Underlying HTTP client evaluates system properties, e.g. proxy settings

- pom.xml
Upgrade org.camunda.community:community-hub-release-parent to 2.0.1
> [Backport 1110 to release/8.5] chore: upgrade org.camunda.community:community-hub-release-parent to 2.0.1

- spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/CommonClientConfiguration.java
This pull request introduces a small enhancement to the `configureOperateIdentityContainer` method in the `CommonClientConfiguration` class. The change adds support for configuring an additional property, `resource`, in the `IdentityConfiguration` object.
* [`CommonClientConfiguration.java`](diffhunk://#diff-bbb3ae62bfdde155c24385e9555b64273f43b0daa719cbb81b902080668e2655R292): Added a call to `.withResource(identityConfigurationFromProperties.getResource())` to include the `resource` property in the `IdentityConfiguration` setup.
> feat: add resource to identity config
